Delete Course Function
uwstout-cs458-s22/advisor001-api pull request #65
Opened 2022-03-05 15:43 UTC by bvoigt00

2022-03-07 02:31 UTC, huseinr2493 commented
I'm not sure it makes sense for the model functions to be returning strings like `'the user was deleted'` and `'the course was deleted'`, since those messages never get sent over the network and only the backend devs would ever see them. Maybe `true` or `{}`?

2022-03-08 00:00 UTC, Slad3 requested changes
I agree with Rahmi, I would change the return value in deleteCourse from 'the course was deleted' to a straight up boolean value

2022-03-08 00:26 UTC, ErikDrake27 commented
I say this is my fault, I was unsure how to word the expected return values, so I just wrote what I thought would be helpful for the devs to see.

2022-03-09 22:47 UTC, Slad3 approved these changes

2022-03-10 04:18 UTC, huseinr2493 approved these changes

2022-03-10 04:21 UTC, merged